#!/usr/bin/env python3
"""Materialize or update a namespaced copy of this workspace pack in a project.

This is intentionally a copy operation, not a Git clone or submodule. The
source pack's own ``_agent_ops/`` is project-specific working memory and must
never become the target project's starting memory.

Every installed copy carries a ``PACK_VERSION`` stamp. Without it a project has
no way to say which pack it is running, so a bug fixed in the pack stays live in
every copy made before the fix, invisibly.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path


sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from scan_deps import looks_like_pack  # noqa: E402
from source_state import worktree_is_clean  # noqa: E402


DEFAULT_FOLDER = "ai-agent-workspace-pack"
EXCLUDED_NAMES = {".git", "_agent_ops", "__pycache__", ".pytest_cache"}
PACK_VERSION_FILE = "PACK_VERSION"
STAMP_HEADER = (
    "# Generated by scripts/embed_pack.py. Identifies the pack revision this\n"
    "# project is running. Do not hand-edit: refresh it with --update.\n"
)


def safe_folder(value: str) -> Path:
    folder = Path(value.replace("\\", "/"))
    if not value or folder.is_absolute() or any(part == ".." for part in folder.parts) or str(folder) in {"", "."}:
        raise ValueError("--folder must be a non-empty path inside --target")
    return folder


def ignore_source_state(directory: str, names: list[str]) -> set[str]:
    """Exclude source checkout state while retaining every pack instruction."""

    del directory
    return {name for name in names if name in EXCLUDED_NAMES or name.endswith(".pyc")}


def git_output(root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=str(root),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def source_version(source: Path) -> str:
    """Revision of the pack being installed, honest about an unclean source."""

    revision = git_output(source, ["rev-parse", "--short", "HEAD"])
    if not revision:
        return "unknown"
    return f"{revision}-dirty" if git_output(source, ["status", "--porcelain"]) else revision


def read_stamp(destination: Path) -> str:
    """The installed pack revision, or an empty string when unstamped."""

    stamp = destination / PACK_VERSION_FILE
    if not stamp.is_file():
        return ""
    for line in stamp.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("version:"):
            return line.split(":", 1)[1].strip()
    return ""


def write_stamp(destination: Path, version: str, previous: str = "") -> None:
    lines = [STAMP_HEADER, f"version: {version}", f"installed: {date.today().isoformat()}"]
    if previous:
        lines.append(f"previous: {previous}")
    (destination / PACK_VERSION_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")


def pack_relative_files(source: Path) -> set[Path]:
    """Every file this pack ships, as paths relative to the pack root."""

    found: set[Path] = set()
    for path in source.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(source)
        if any(part in EXCLUDED_NAMES for part in relative.parts) or path.suffix == ".pyc":
            continue
        found.add(relative)
    return found


def refresh_pack_files(source: Path, destination: Path) -> tuple[int, list[Path]]:
    """Overwrite pack content in place, leaving `_agent_ops/` untouched.

    Returns the number of files written and the stale files removed: content
    dropped or renamed in a later pack revision would otherwise linger forever
    in every project that installed an earlier one.
    """

    shipped = pack_relative_files(source)
    for relative in sorted(shipped):
        target_path = destination / relative
        target_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / relative, target_path)

    owned_roots = {relative.parts[0] for relative in shipped}
    stale: list[Path] = []
    for path in sorted(destination.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(destination)
        if relative.parts[0] in EXCLUDED_NAMES or relative.name == PACK_VERSION_FILE:
            continue
        if relative.parts[0] in owned_roots and relative not in shipped:
            path.unlink()
            stale.append(relative)
    return len(shipped), stale


def initialize(destination: Path, target: Path, folder: Path, bridge: bool) -> int:
    command = [
        sys.executable,
        "-B",
        str(destination / "scripts" / "init_project_ops.py"),
        "--target",
        str(target),
        "--embedded-folder",
        folder.as_posix(),
    ]
    if bridge:
        command.append("--install-agents-bridge")
    return subprocess.run(command, cwd=str(target), text=True, check=False).returncode


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Copy this pack into a project, or update a copy already installed there."
    )
    parser.add_argument("--target", required=True, help="Target project directory.")
    parser.add_argument("--folder", default=DEFAULT_FOLDER, help="Pack folder inside the target project.")
    parser.add_argument(
        "--update",
        action="store_true",
        help=(
            "Refresh a pack already installed at --folder. Overwrites pack content and removes "
            "files this revision no longer ships; never touches _agent_ops/."
        ),
    )
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="Update even though the target worktree has uncommitted changes.",
    )
    args = parser.parse_args()

    target = Path(args.target).expanduser().resolve()
    if not target.exists() or not target.is_dir():
        parser.error(f"Target must be an existing directory: {target}")
    try:
        folder = safe_folder(args.folder)
    except ValueError as error:
        parser.error(str(error))

    source = Path(__file__).resolve().parents[1]
    destination = target / folder
    version = source_version(source)

    if not args.update:
        if destination.exists():
            parser.error(
                f"Destination already exists: {destination}\n"
                "       Re-run with --update to refresh the installed pack in place."
            )
        shutil.copytree(source, destination, ignore=ignore_source_state)
        write_stamp(destination, version)
        code = initialize(destination, target, folder, bridge=True)
        if code != 0:
            print(
                f"BLOCKED: copied pack remains at {destination}; initialization failed without removing it.",
                file=sys.stderr,
            )
            return code or 1
        print(f"EMBEDDED PACK: {destination} (version {version})")
        print("Source .git and source _agent_ops were excluded; a fresh nested ops folder was initialized.")
        return 0

    if not destination.is_dir() or not looks_like_pack(destination):
        parser.error(f"No installed pack to update at {destination}; run without --update to install one.")
    if destination == source:
        parser.error("Refusing to update this pack's own source checkout.")

    clean = worktree_is_clean(target)
    if clean is None and not args.allow_dirty:
        parser.error(
            "Target is not a Git repository, so an update would not be revertible. "
            "Commit it to Git first, or pass --allow-dirty to accept that risk."
        )
    if clean is False and not args.allow_dirty:
        parser.error(
            "Target worktree has uncommitted changes. Commit or stash them first so the update "
            "is revertible, or pass --allow-dirty."
        )

    previous = read_stamp(destination)
    if previous == version:
        print(f"UP TO DATE: {destination} already runs pack version {version}.")
        print("Refreshing content anyway is safe: re-run after committing if you edited the pack in place.")
    written, stale = refresh_pack_files(source, destination)
    write_stamp(destination, version, previous)
    print(f"UPDATED PACK: {destination}")
    print(f"  version: {previous or 'unstamped'} -> {version}")
    print(f"  files written: {written}")
    if stale:
        print(f"  stale files removed: {len(stale)}")
        for relative in stale[:10]:
            print(f"    {relative.as_posix()}")
        if len(stale) > 10:
            print(f"    ... {len(stale) - 10} more")
    print("  project memory: _agent_ops/ untouched")

    code = initialize(destination, target, folder, bridge=False)
    if code != 0:
        print(
            "BLOCKED: pack content was refreshed but re-initialization failed. "
            "Nothing in _agent_ops/ was modified.",
            file=sys.stderr,
        )
        return code or 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
