#!/usr/bin/env python3
"""Initialize an AI-agent project operations folder in a target project."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Running a tool must never leave __pycache__ inside someone else's repository.
sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))


TEMPLATE_MAP = {
    "INDEX.template.md": "INDEX.md",
    "PROJECT_CONTEXT_CARD.template.md": "PROJECT_CONTEXT_CARD.md",
    "SESSION_PROTOCOL.template.md": "SESSION_PROTOCOL.md",
    "SESSION_BRIEF.template.md": "SESSION_BRIEF.md",
    "CURRENT_TASK.template.md": "CURRENT_TASK.md",
    "IMPLEMENTATION_LOG.template.md": "IMPLEMENTATION_LOG.md",
    "DECISION_LOG.template.md": "DECISION_LOG.md",
    "RISK_REGISTER.template.md": "RISK_REGISTER.md",
    "PHASE_ROADMAP.template.md": "PHASE_ROADMAP.md",
    "OPERATING_RULES.template.md": "OPERATING_RULES.md",
}

# Tools copied into <ops>/tools/ so the target project can run them without the
# pack being present. Installing the pack "next to" a project used to leave the
# project unable to run any of this: `python scripts/session_start.py` only
# works from inside the pack. These are stdlib-only and cross-import each other,
# so they are copied as a set. init_project_ops.py itself is NOT copied -- it
# needs the pack's core-context/ templates, which do not travel with it.
RUNTIME_TOOLS = [
    "scan_deps.py",
    "generate_context_card.py",
    "source_state.py",
    "generate_repo_map.py",
    "build_code_index.py",
    "refresh_repo_map.py",
    "explore.py",
    "session_start.py",
    "summarize_implementation_log.py",
    "check_repo_hygiene.py",
]

# Hybrid git policy: durable project memory is tracked so it survives a clone;
# session-scoped scratch stays local so it never noises up a diff or leaks
# working notes into a public repository.
SESSION_SCOPED = [
    "SESSION_BRIEF.md",
    "CURRENT_TASK.md",
    "LOG_SUMMARY.md",
    "code_index.json",
]

OPS_GITIGNORE = """# Hybrid policy for _agent_ops/ (see INDEX.md).
#
# Ignored below: session-scoped scratch and derived files. SESSION_BRIEF and
# CURRENT_TASK are machine-local working notes that change every session;
# LOG_SUMMARY is regenerated from the log, so tracking it would only create
# merge noise.
#
# Everything else in this folder IS tracked on purpose: the context card, repo
# map, implementation log and its archive, handoff, decisions, risks, roadmap,
# and operating rules are durable project memory that must survive a clone.
# Never put secrets or private data in tracked files.

SESSION_BRIEF.md
CURRENT_TASK.md
LOG_SUMMARY.md

# Derived build artifact: rebuilt from source by build_code_index.py, can reach
# tens of MB on a large repo, and would conflict on every merge. REPO_MAP.md is
# the small human-readable view of it and IS tracked.
code_index.json

# Bytecode from running tools/. The tools themselves ARE tracked on purpose: a
# teammate who clones this project then has working tooling without the pack.
__pycache__/
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def copy_template(source: Path, destination: Path, force: bool) -> str:
    if destination.exists() and not force:
        return f"SKIP existing: {destination}"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return f"WRITE: {destination}"


def write_if_absent(destination: Path, content: str, force: bool) -> str:
    if destination.exists() and not force:
        return f"SKIP existing: {destination}"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return f"WRITE: {destination}"


TOOLS_README = """# Tools

Copies of the workspace-pack scripts, so this project can run them without the
pack being installed. Do not hand-edit: re-running `init_project_ops.py`
overwrites this folder. Fix the pack instead.

Run every tool from the project root:

```bash
python _agent_ops/tools/session_start.py --root .
python _agent_ops/tools/explore.py --symbol <name>

python _agent_ops/tools/refresh_repo_map.py --root . --stage
```

For an authorized source commit, run the refresh helper after staging source and
tests. It rebuilds the index and Repo Map once, then stages only REPO_MAP.md.
"""

TARGET_AGENTS_MD = """# AGENTS.md

Agent instructions for this project. Generated by the AI agent workspace pack.
Edit it freely -- it is never overwritten once it exists.

<!-- PACK_MODE -->

## Start Every Session Here

```bash
python _agent_ops/tools/session_start.py --root .
```

Read-only. It prints session continuity, the git delta since memory was last
verified, stale memory, unfilled placeholders, and log size. If it reports
CONTINUATION, read `_agent_ops/HANDOFF.md` before anything else.

Then load only `_agent_ops/SESSION_BRIEF.md`, `_agent_ops/OPERATING_RULES.md`,
and `_agent_ops/CURRENT_TASK.md` when a task is already in progress.
`_agent_ops/INDEX.md` is the read-order router for the rest of that folder. Do
not load every file in it on every turn.

## Locate Code Without Grepping

Read `_agent_ops/REPO_MAP.md` first: modules, routes, and the files with the
widest blast radius, in one size-capped read. For symbol-level questions, query
the code graph instead of grepping:

```bash
python _agent_ops/tools/explore.py --symbol <name>   # definitions, callers, callees
python _agent_ops/tools/explore.py --path <a> <b>    # how control reaches a symbol
python _agent_ops/tools/explore.py --impact <name>   # blast radius + tests to run
python _agent_ops/tools/explore.py --entrypoints     # routes and unreferenced symbols
```

Every edge carries a provenance tag: `exact`, `heuristic`, `ambiguous`, `weak`.
Treat the last three as leads to confirm by reading code, never as fact. Static
analysis cannot see dynamic dispatch, DI wiring, reflection, or runtime
registries, so an impact result is the MINIMUM blast radius, never the maximum.

Rebuild both after significant code changes:

```bash
python _agent_ops/tools/build_code_index.py --root . --output _agent_ops/code_index.json --force
python _agent_ops/tools/generate_repo_map.py --root . --output _agent_ops/REPO_MAP.md --force
```

## How To Work

- Lead with the answer, then the reasoning. No preamble, no filler.
- Say what you understood and what context is missing. Ask at most one
  clarifying question before acting on ambiguous input.
- Ask before writing or modifying files unless autonomous mode was confirmed.
- Never use `git add .`; stage explicit files only. Ask before destructive
  actions. Never commit secrets, datasets, model files, or local logs.
- Keep `_agent_ops/CURRENT_TASK.md` current DURING a task, not only at the end:
  files touched, approaches ruled out with their evidence, next step. That file
  is what survives a mid-task context compaction.
- A task prompt defines deliverable scope, not durable recordkeeping. Before a
  completion report, classify the work actually performed under the session
  protocol; a filename omitted from the prompt never makes a triggered record
  not needed.
- Append the implementation log for implementation, test, audit, gate, or
  verification evidence. Update the project context card for durable
  phase/milestone state and the decision log for material trade-offs. Write
  these records before printing the Closure Receipt; an explicit user opt-out
  must be reported as a constraint, not as not needed.
- Before a local commit that includes staged project code, run the repo-map
  refresh helper with --stage after tests and before git commit. It rebuilds the
  symbol index and REPO_MAP.md once, then stages only REPO_MAP.md. If the
  managed pre-commit hook is installed, it enforces the repo-map safety gate and
  blocks an index/worktree mismatch.

## Coding Standard

- One responsibility per change. A function, a file, a commit does one thing.
- No overlapping side effects: two code paths must not write the same state
  without one clear owner. That is the main cause of "fixing one bug creates
  another".
- Keep files small enough to reason about. Split a file before it passes ~400
  lines and a function before ~50. Split along a responsibility boundary and
  name the boundary you used; never split by line count alone.
- Reuse existing logic instead of duplicating it. Look for an existing helper
  before writing a new one.
"""

EMBEDDED_MODE = """## Pack Mode: Embedded

This repository contains the full workspace pack (`TEAM_ROUTER.md` is present).
Treat `@start-here` as a literal session marker. The managed bridge below is
the project entry point for routing it safely.

<!-- AI_AGENT_WORKSPACE_PACK:BEGIN v1 -->
## AI Agent Workspace Pack

Instructions outside this managed block remain authoritative. This block is an
approved, narrowly scoped amendment for the workflow below.

When a user message starts with `@start-here`, read `START_HERE.md` and
`TEAM_ROUTER.md`, then load only the selected team's `SKILL.md`.

Pack instructions may add workflow but must not weaken existing project rules.
`@start-here` authorizes only `_agent_ops/` writes defined by the pack; source,
configuration, dependencies, git, destructive actions, and external services
remain governed by the project's existing rules.
<!-- AI_AGENT_WORKSPACE_PACK:END v1 -->

If `_agent_ops/` is missing, bootstrap it with
`python scripts/init_project_ops.py --target .`; that creates only agent-ops
state, never source or git changes. After bootstrap, use the local tools under
`_agent_ops/tools/` for deterministic checks and graph queries.
"""

RUNTIME_ONLY_MODE = """## Pack Mode: Runtime-only

No `TEAM_ROUTER.md` was present when this file was generated. Use the local
`_agent_ops/` records and tools normally, but do not claim that named pack teams
or `@start-here` routing instructions are available unless the user supplies an
embedded pack or an explicit team playbook.
"""

AGENTS_BRIDGE_BEGIN = "<!-- AI_AGENT_WORKSPACE_PACK:BEGIN v1 -->"
AGENTS_BRIDGE_END = "<!-- AI_AGENT_WORKSPACE_PACK:END v1 -->"
AGENTS_BRIDGE_PREFIX = "<!-- AI_AGENT_WORKSPACE_PACK:"
AGENTS_BRIDGE = """<!-- AI_AGENT_WORKSPACE_PACK:BEGIN v1 -->
## AI Agent Workspace Pack

Instructions outside this managed block remain authoritative. This block is an
approved, narrowly scoped amendment for the workflow below.

When a user message starts with `@start-here`, read `START_HERE.md` and
`TEAM_ROUTER.md`, then load only the selected team's `SKILL.md`.

Pack instructions may add workflow but must not weaken existing project rules.
`@start-here` authorizes only `_agent_ops/` writes defined by the pack; source,
configuration, dependencies, git, destructive actions, and external services
remain governed by the project's existing rules.
<!-- AI_AGENT_WORKSPACE_PACK:END v1 -->"""


def write_tools(ops_dir: Path) -> list[str]:
    """Copy the runtime tools into the project so it stops depending on the pack.

    Refreshed on every init even without --force: these are pack-owned derived
    copies, and a stale copy that silently disagrees with the pack is worse than
    a noisy overwrite. Nothing the user authored lives in this folder.
    """
    source_dir = Path(__file__).resolve().parent
    tools_dir = ops_dir / "tools"
    tools_dir.mkdir(parents=True, exist_ok=True)
    results: list[str] = []
    for name in RUNTIME_TOOLS:
        source = source_dir / name
        if not source.exists():
            results.append(f"WARN missing tool: {source}")
            continue
        destination = tools_dir / name
        action = "UPDATE" if destination.exists() else "WRITE"
        shutil.copyfile(source, destination)
        results.append(f"{action}: {destination}")
    results.append(write_if_absent(tools_dir / "README.md", TOOLS_README, True))
    return results


REPO_MAP_HOOK_MARKER = "# AI_AGENT_OPS_REPO_MAP_PRE_COMMIT v1"
REPO_MAP_HOOK = """#!/bin/sh
# AI_AGENT_OPS_REPO_MAP_PRE_COMMIT v1
set -eu

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
TOOL="$ROOT/_agent_ops/tools/refresh_repo_map.py"
if [ ! -f "$TOOL" ]; then
  echo "BLOCKED: missing _agent_ops/tools/refresh_repo_map.py" >&2
  exit 2
fi

if python -c "import sys" >/dev/null 2>&1; then
  exec python "$TOOL" --root "$ROOT" --stage
fi
if python3 -c "import sys" >/dev/null 2>&1; then
  exec python3 "$TOOL" --root "$ROOT" --stage
fi
if py -3 -c "import sys" >/dev/null 2>&1; then
  exec py -3 "$TOOL" --root "$ROOT" --stage
fi
echo "BLOCKED: no working Python interpreter found for repo-map hook" >&2
exit 2
"""


def install_repo_map_hook(target: Path) -> str:
    """Install only the pack-managed pre-commit hook; preserve any user hook."""

    result = subprocess.run(
        ["git", "rev-parse", "--git-path", "hooks/pre-commit"],
        cwd=str(target),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if result.returncode != 0:
        return "SKIP repo-map hook: target is not a Git repository."

    hook_path = Path(result.stdout.strip())
    if not hook_path.is_absolute():
        hook_path = target / hook_path
    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8", errors="ignore")
        if REPO_MAP_HOOK_MARKER not in existing:
            return f"WARN existing pre-commit hook preserved: {hook_path}"
        action = "UPDATE"
    else:
        hook_path.parent.mkdir(parents=True, exist_ok=True)
        action = "WRITE"

    with hook_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(REPO_MAP_HOOK)
    if os.name != "nt":
        hook_path.chmod(hook_path.stat().st_mode | 0o100)
    return f"{action}: managed repo-map pre-commit hook: {hook_path}"


def target_agents_content(target: Path) -> str:
    """One generated entry point, accurate for embedded and runtime-only installs."""
    mode = EMBEDDED_MODE if (target / "TEAM_ROUTER.md").is_file() else RUNTIME_ONLY_MODE
    return TARGET_AGENTS_MD.replace("<!-- PACK_MODE -->", mode.rstrip())


def write_target_agents_md(target: Path) -> str:
    """Drop an AGENTS.md at the project root if it has none.

    This is the file Codex, Claude Code, Cursor, and friends pick up on their
    own. Without it, everything installed under _agent_ops/ is invisible unless
    the user remembers to point at it every session. Never overwritten: a
    project that already has one has already made this decision.
    """
    destination = target / "AGENTS.md"
    return write_if_absent(destination, target_agents_content(target), False)


def agents_bridge_status(target: Path) -> tuple[str, str]:
    """Return a structural status for the optional host-owned AGENTS bridge."""
    destination = target / "AGENTS.md"
    if not destination.exists():
        return "MISSING", "AGENTS.md does not exist"
    try:
        content = destination.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        return "CORRUPT", f"cannot read AGENTS.md safely: {error}"

    begins = content.count(AGENTS_BRIDGE_BEGIN)
    ends = content.count(AGENTS_BRIDGE_END)
    any_marker = AGENTS_BRIDGE_PREFIX in content
    if begins == 0 and ends == 0:
        if any_marker:
            return "CORRUPT", "unsupported bridge marker or version"
        return "MISSING", "no managed bridge block"
    if begins != 1 or ends != 1:
        return "CORRUPT", "expected exactly one BEGIN and one END marker"

    start = content.index(AGENTS_BRIDGE_BEGIN)
    end_start = content.index(AGENTS_BRIDGE_END)
    if end_start < start:
        return "CORRUPT", "END marker appears before BEGIN marker"
    end = end_start + len(AGENTS_BRIDGE_END)
    if content[start:end] == AGENTS_BRIDGE:
        return "INSTALLED", "managed bridge v1"
    return "OUTDATED", "managed block differs from bridge v1"


def install_agents_bridge(target: Path) -> str:
    """Append or update only the pack-owned bridge block in AGENTS.md."""
    destination = target / "AGENTS.md"
    status, detail = agents_bridge_status(target)
    if status == "CORRUPT":
        return f"AGENTS BRIDGE: CORRUPT ({detail}); not modified"
    if status == "INSTALLED":
        return "AGENTS BRIDGE: INSTALLED (managed bridge v1; unchanged)"
    if status == "MISSING":
        content = destination.read_text(encoding="utf-8")
        separator = "" if content.endswith("\n") else "\n"
        destination.write_text(content + separator + "\n" + AGENTS_BRIDGE + "\n", encoding="utf-8")
        return "AGENTS BRIDGE: INSTALLED (managed bridge v1 appended)"

    content = destination.read_text(encoding="utf-8")
    start = content.index(AGENTS_BRIDGE_BEGIN)
    end = content.index(AGENTS_BRIDGE_END, start) + len(AGENTS_BRIDGE_END)
    destination.write_text(content[:start] + AGENTS_BRIDGE + content[end:], encoding="utf-8")
    return "AGENTS BRIDGE: INSTALLED (managed bridge v1 updated)"


def write_code_index(target: Path, ops_dir: Path, force: bool) -> str:
    """Build the symbol-level index that scripts/explore.py queries."""
    destination = ops_dir / "code_index.json"
    if destination.exists() and not force:
        return f"SKIP existing: {destination}"
    try:
        import json  # noqa: PLC0415

        from build_code_index import build_index  # noqa: PLC0415

        index = build_index(target)
        destination.write_text(json.dumps(index, separators=(",", ":")), encoding="utf-8")
        return (
            f"WRITE: {destination} "
            f"({len(index['symbols'])} symbols, {len(index['edges'])} edges)"
        )
    except Exception as error:  # noqa: BLE001 - report, do not abort init
        return (
            f"WARN could not build {destination}: {error}"
            "\n"
            "     Run scripts/build_code_index.py manually if you want "
            "symbol-level exploration."
        )


def write_repo_map(target: Path, ops_dir: Path, force: bool) -> str:
    """Generate the codegraph-lite map. Never fatal: the pack must stay usable
    on repos where this scan cannot run."""
    destination = ops_dir / "REPO_MAP.md"
    if destination.exists() and not force:
        return f"SKIP existing: {destination}"
    try:
        from generate_repo_map import render_map  # noqa: PLC0415
        from scan_deps import build_graph  # noqa: PLC0415

        graph = build_graph(target)
        destination.write_text(render_map(target, graph, 25, 15), encoding="utf-8")
        return f"WRITE: {destination} ({len(graph)} code files indexed)"
    except Exception as error:  # noqa: BLE001 - report, do not abort init
        return (
            f"WARN could not generate {destination}: {error}\n"
            "     Run scripts/generate_repo_map.py manually, or describe the "
            "layout in PROJECT_CONTEXT_CARD.md."
        )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create _agent_ops/ project memory files in a target project."
    )
    parser.add_argument("--target", required=True, help="Target project directory.")
    parser.add_argument(
        "--ops-folder",
        default="_agent_ops",
        help="Operations folder name to create inside the target project.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing ops files.",
    )
    parser.add_argument(
        "--no-repo-map",
        action="store_true",
        help="Skip generating REPO_MAP.md (useful for very large repositories).",
    )
    parser.add_argument(
        "--no-index",
        action="store_true",
        help="Skip building code_index.json (the symbol-level graph).",
    )
    parser.add_argument(
        "--no-tools",
        action="store_true",
        help="Do not copy the runtime tools into <ops>/tools/.",
    )
    parser.add_argument(
        "--install-repo-map-hook",
        action="store_true",
        help=(
            "Install the managed pre-commit hook that refreshes and explicitly stages "
            "REPO_MAP.md for staged project-code commits. Never overwrites another hook."
        ),
    )
    parser.add_argument(
        "--no-agents-md",
        action="store_true",
        help="Do not create AGENTS.md at the project root when it is missing.",
    )
    parser.add_argument(
        "--install-agents-bridge",
        action="store_true",
        help=(
            "Explicitly append or update the managed workspace-pack bridge in an "
            "existing AGENTS.md. Requires an embedded pack and never changes text "
            "outside the bridge markers."
        ),
    )
    parser.add_argument(
        "--check-agents-bridge",
        action="store_true",
        help="Read-only bridge check; exits nonzero unless the managed bridge is installed.",
    )
    args = parser.parse_args()
    if args.install_repo_map_hook and args.no_tools:
        parser.error("--install-repo-map-hook requires the runtime tools.")
    if args.install_agents_bridge and args.no_agents_md:
        parser.error("--install-agents-bridge cannot be combined with --no-agents-md.")
    if args.install_agents_bridge and args.check_agents_bridge:
        parser.error("Choose either --install-agents-bridge or --check-agents-bridge.")

    target = Path(args.target).expanduser().resolve()
    if not target.exists():
        parser.error(f"Target does not exist: {target}")
    if not target.is_dir():
        parser.error(f"Target is not a directory: {target}")

    embedded = (target / "TEAM_ROUTER.md").is_file()
    if args.check_agents_bridge:
        status, detail = agents_bridge_status(target)
        print(f"AGENTS BRIDGE: {status} ({detail})")
        return 0 if status == "INSTALLED" else 1
    if args.install_agents_bridge and not embedded:
        parser.error("--install-agents-bridge requires an embedded pack with TEAM_ROUTER.md.")

    templates_dir = repo_root() / "core-context"
    if not templates_dir.exists():
        parser.error(f"Cannot find template directory: {templates_dir}")

    ops_dir = target / args.ops_folder
    ops_dir.mkdir(parents=True, exist_ok=True)

    print(f"Target: {target}")
    print(f"Ops folder: {ops_dir}")

    for template_name, output_name in TEMPLATE_MAP.items():
        source = templates_dir / template_name
        if not source.exists():
            print(f"WARN missing template: {source}")
            continue
        print(copy_template(source, ops_dir / output_name, args.force))

    phase_dir = ops_dir / "phase_context_cards"
    phase_dir.mkdir(exist_ok=True)
    print(
        write_if_absent(
            phase_dir / "README.md",
            "# Phase Context Cards\n\n"
            "Store one phase context card per completed or active phase.\n\n"
            "Suggested name: `PHASE_001_<short-name>.md`.\n",
            args.force,
        )
    )

    archive_dir = ops_dir / "archive"
    archive_dir.mkdir(exist_ok=True)
    print(
        write_if_absent(
            archive_dir / "README.md",
            "# Archive\n\n"
            "Rotated implementation-log entries land here so the active log stays\n"
            "small enough to read cheaply. Read these only when investigating\n"
            "something older than the retained window.\n",
            args.force,
        )
    )

    print(write_if_absent(ops_dir / ".gitignore", OPS_GITIGNORE, args.force))

    if args.no_tools:
        print(f"SKIP tools (--no-tools): {ops_dir / 'tools'}")
    else:
        for line in write_tools(ops_dir):
            print(line)
    if args.install_repo_map_hook:
        print(install_repo_map_hook(target))

    # Index BEFORE map, not after: the map reads code_index.json to fill in its
    # Symbol Graph section, so building it second made a fresh install report
    # "Symbol Graph: Not built" even though the index landed moments later.
    if args.no_index:
        print(f"SKIP code index (--no-index): {ops_dir / 'code_index.json'}")
    else:
        print(write_code_index(target, ops_dir, args.force))
    if args.no_repo_map:
        print(f"SKIP repo map (--no-repo-map): {ops_dir / 'REPO_MAP.md'}")
    else:
        print(write_repo_map(target, ops_dir, args.force))

    agents_existed = (target / "AGENTS.md").exists()
    if args.no_agents_md:
        print(f"SKIP AGENTS.md (--no-agents-md): {target / 'AGENTS.md'}")
    else:
        print(write_target_agents_md(target))
        if args.install_agents_bridge:
            print(install_agents_bridge(target))
        elif embedded and agents_existed:
            status, detail = agents_bridge_status(target)
            if status == "MISSING":
                print(
                    "WARN embedded pack detected but AGENTS bridge is missing. "
                    "Re-run with --install-agents-bridge to add the managed bridge."
                )
            else:
                print(f"AGENTS BRIDGE: {status} ({detail})")

    print("")
    print("Done. Existing files were preserved unless --force was used.")
    print("Session-scoped files are gitignored by _agent_ops/.gitignore:")
    print("  " + ", ".join(SESSION_SCOPED))
    print("Everything else in _agent_ops/ is tracked on purpose.")
    print("")
    print("Next steps, run from inside the project (no pack needed):")
    print(f"  cd {target}")
    print("  python _agent_ops/tools/session_start.py --root .")
    print("  python _agent_ops/tools/explore.py --symbol <name>")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
